name: RGB Background Colour App

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
      - feature/*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: powellrhys/react-projects-rgb-background-colour

jobs:
  build-and-push-image:
    name: Build & Push Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Lint with yamllint
        run: |
          yamllint -c .yamllint.yml .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build image: ${{ github.repository }}"
        working-directory: './rgb_background_colour'
        run: docker build -f Dockerfile -t $REGISTRY/$IMAGE_NAME .

      - name: Push Container to GitHub container registry
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: DockerHub Login
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push Container to DockerHub Container registry
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:latest $IMAGE_NAME:latest
          docker push $IMAGE_NAME
